language: go
go_import_path: github.com/windard/godown

matrix:
  fast_finish: true
  include:
  - go: 1.13.x
  - go: master

git:
  depth: 10

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
  - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi

script:
  - make prepare
  - make check
  - make test
  - make clean

after_success:
  - bash <(curl -s https://codecov.io/bash)
