name: Release
on:
  create:
    tags:
    - v*

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      VERSION: ${GITHUB_REF##*/}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Test
        run: go test -v .

      - name: Build Linux
        run: |
          make build
          make package
        env:
          GOOS: linux

      - name: Build Mac
        run: |
          make build
          make package
        env:
          GOOS: darwin

      - name: Build Windows
        run: |
          make build
          make package
        env:
          GOOS: windows

      - name: Upload Release Asset
        id: upload-release-asset
        run: |
          set -x
          sha256sum *.tar.gz > sha256sum.txt
          assets=("-a" "sha256sum.txt")
          for asset in ./*.tar.gz; do
            assets+=("-a" "$asset")
          done
          hub release create "${assets[@]}" -m "$VERSION" "$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
